# Generated by Django 3.0.7 on 2020-06-16 04:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='like_movie_reviews_users',
            field=models.ManyToManyField(related_name='like_movie_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
