# Generated by Django 3.0.7 on 2020-06-13 11:41

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_files', imagekit.models.fields.ProcessedImageField(upload_to=reviews.models.image_path)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_images', to='reviews.Review')),
            ],
        ),
    ]
