# Generated by Django 3.0.7 on 2020-06-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='userRating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
