# Generated by Django 3.0.7 on 2020-06-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_userrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='pubDate',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='userRating',
            field=models.TextField(),
        ),
    ]
